### PR TITLE
PHP7 support

### PR DESCRIPTION
**Pull request by enov**

### CODE REVIEW

**Comment by shadowhand** [comment]
:+1: but why do we need to continue supporting this repo?

**Comment by enov** [comment]
I think we should deprecate this in 3.4 and then drop it later.

**Comment by shadowhand** [comment]
I wouldn't even bother with a deprecation in 3.4. It's not a tool that would be used in production and I highly doubt any of it would change. Just deprecate it in the next release of 3.3 and stop maintaining it.

**Comment by acoulton** [comment]
+1 for stopping support for this following the next 3.3 release.

**Pull request merged**
